version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource  # SQLiteプラグインのインストール
    volumes:
      - './grafana_storage:/var/lib/grafana'
      - './sql/:/opt/sqlite/'  # SQLiteデータベースを別ディレクトリにマウント
    ports:
      - '3000:3000'  # 待受ポート番号を変更したい場合は : の左側を変更

volumes: # データの永続化
  grafana_storage: {}

services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 15432:5432
    env_file:
      - .env-postgres
    volumes: # 名前付きボリュームの割り当て定義を追加
      - db-data:/var/lib/postgresql/data

# 名前付きボリュームの定義を追加
volumes:
  db-data:
    driver: local